name: React Examples Workflow

on:
  push:
    branches: [ $default-branch, real-time_text_component ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Make env file
        run: cp .env.example .env
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: tutorial
          DB_USERNAME: root
          DB_PASSWORD:
      - name: MySQL - Check server version
        run: mysql -V
      
      - name: MySQL - Load from community actions
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - name: MySQL - Connect to server
        run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'

      - name: Install Composer depencencies
        run: composer install
      
      - name: Clear cache
        run: php artisan config:cache
        
      - name: Run migrations
        run: php artisan migrate

