name: React Examples Workflow

on:
  push:
    branches: [ $default-branch, real-time_text_component ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Composer depencencies
        run: composer install
        
      - name: Make env file
        run: cp .env.example .env
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: tutorial
          DB_USERNAME: root
          DB_PASSWORD:
      - name: MySQL rename file to connection
        run: mv /etc/mysql/my.cnf /etc/mysql/otherName.cnf
      - name: MySQL login
        run: mysql -u -p
      #- name: Run migrations
      #  run: php artisan migrate

