name: React Examples Workflow

on:
  push:
    branches: [ $default-branch, real-time_text_component ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install depencencies
        run: composer install
        
      - name: Make env file
        services:
            mysql:
              image: mysql:5.7
              env:
                MYSQL_DATABASE: database_ci
                MYSQL_USER: user
                MYSQL_PASSWORD: secret
                MYSQL_ROOT_PASSWORD: secretroot
              ports:
                - 33306:3306
              options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        run: cp .env.example .env
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: tutorial
          DB_USERNAME: root
          DB_PASSWORD:
    
      - name: Run migrations
        run: php artisan migrate

