name: React Examples Workflow

on:
  push:
    branches: [ $default-branch, real-time_text_component ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Composer depencencies
        run: composer install
        
      - name: Make env file
        run: cp .env.example .env
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: tutorial
          DB_USERNAME: root
          DB_PASSWORD:
      - name: MySQL check server version
        run: mysql -V
      - run: mysql start
      - name: MySQL rename file to connection
        run: mysql -h 127.0.0.1 -P 3306 -u root tutorial

      #- name: Run migrations
      #  run: php artisan migrate

