name: React Examples CI

on:
  push:
    branches: [ $default-branch, real-time_text_component ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
